import Head from 'next/head'
import Image from 'next/image'
import { Roboto } from 'next/font/google';

const inter = Roboto({ subsets: ['latin'], weight:['400'] })

const links = [
  {

    title: "CPC",
    description: " link to Conservancy website ",
    url: 'https://www.centennialparkconservancy.com'
  }
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>
          Centennial Park Conservancy
          </h1>
        <h3>
          this is the CPC dashboard website
        </h3>
        </div>
        <div>
          {links.map(link => (
            <a key={link.url} href = {link.url}>
              <span> {link.title}</span>
              <span>{link.description}</span>
            </a>
          ))}
        </div>
      </main>
    </>
  )
}
